# Week 4 · Day 3 — Pandas Exercises

Practice for Series, DataFrames, selection, `describe()`, data types, and everyday operations.

**How to work:**
- Fill in each cell where you see `...` or a `# TODO`.
- Run your cell and check the output makes sense.

Setup — run this first.

In [181]:
import numpy as np
import pandas as pd

# The same Titanic-style dataset from today's lesson
data = {
    "Survived": [0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1],
    "Pclass":   [3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1],
    "Sex":      ["male","female","female","female","male","male",
                 "male","female","female","female","male","female"],
    "Age":      [22, 38, 26, 35, np.nan, np.nan, 54, 27, 14, 4, 20, 58],
    "Fare":     [7.25, 71.28, 7.92, 53.10, 8.05, 8.46,
                 51.86, 11.13, 30.07, 16.70, 7.85, 26.55],
    "Embarked": ["S","C","S","S","S","Q","S","S","S","S","S","C"],
}
df = pd.DataFrame(data)
df

    Survived  Pclass     Sex   Age   Fare Embarked
0          0       3    male  22.0   7.25        S
1          1       1  female  38.0  71.28        C
2          1       3  female  26.0   7.92        S
3          1       1  female  35.0  53.10        S
4          0       3    male   NaN   8.05        S
5          0       3    male   NaN   8.46        Q
6          0       1    male  54.0  51.86        S
7          0       3  female  27.0  11.13        S
8          1       3  female  14.0  30.07        S
9          1       2  female   4.0  16.70        S
10         0       3    male  20.0   7.85        S
11         1       1  female  58.0  26.55        C

---
## Part 1 — Series

**1.1** Create a Series called `marks` from the list `[85, 72, 90, 66, 78]` with the index labels `["Urdu", "Math", "English", "Physics", "Chemistry"]`.

In [182]:
# TODO 1.1
marks = [85,72,90,66,78]
ind=["Urdu", "Math", "English", "Physics", "Chemistry"]
series=pd.Series(marks,index=ind)
series

Urdu         85
Math         72
English      90
Physics      66
Chemistry    78
dtype: int64

**1.2** Print the mark for `"English"` using its label.

In [183]:
# TODO 1.2
print(series['English'])

90

In [184]:
series.iloc[2]

np.int64(90)

**1.3** Show only the subjects where the mark is above 75.

In [185]:
# TODO 1.3  (hint: boolean filtering)
ser70=(series>75)
series[ser70]

Urdu         85
English      90
Chemistry    78
dtype: int64

**1.4** Build a Series from this dictionary of city populations (millions) and print its mean.
`{"Karachi": 16.0, "Lahore": 11.1, "Faisalabad": 3.2, "Rawalpindi": 2.1}`

In [186]:
# TODO 1.4
pop = {"Karachi": 16.0, "Lahore": 11.1, "Faisalabad": 3.2, "Rawalpindi": 2.1}
print(pop)
print("mean:", (pd.Series(pop.values())).mean())

{'Karachi': 16.0, 'Lahore': 11.1, 'Faisalabad': 3.2, 'Rawalpindi': 2.1}
mean: 8.1

---
## Part 2 — DataFrame basics (use `df` from setup)

**2.1** Display the first 3 rows of `df`.

In [187]:
# The same Titanic-style dataset from today's lesson
data = {
    "Survived": [0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1],
    "Pclass":   [3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1],
    "Sex":      ["male","female","female","female","male","male",
                 "male","female","female","female","male","female"],
    "Age":      [22, 38, 26, 35, np.nan, np.nan, 54, 27, 14, 4, 20, 58],
    "Fare":     [7.25, 71.28, 7.92, 53.10, 8.05, 8.46,
                 51.86, 11.13, 30.07, 16.70, 7.85, 26.55],
    "Embarked": ["S","C","S","S","S","Q","S","S","S","S","S","C"],
}
df = pd.DataFrame(data)
df

    Survived  Pclass     Sex   Age   Fare Embarked
0          0       3    male  22.0   7.25        S
1          1       1  female  38.0  71.28        C
2          1       3  female  26.0   7.92        S
3          1       1  female  35.0  53.10        S
4          0       3    male   NaN   8.05        S
5          0       3    male   NaN   8.46        Q
6          0       1    male  54.0  51.86        S
7          0       3  female  27.0  11.13        S
8          1       3  female  14.0  30.07        S
9          1       2  female   4.0  16.70        S
10         0       3    male  20.0   7.85        S
11         1       1  female  58.0  26.55        C

In [188]:
# TODO 2.1
df.head(3)

   Survived  Pclass     Sex   Age   Fare Embarked
0         0       3    male  22.0   7.25        S
1         1       1  female  38.0  71.28        C
2         1       3  female  26.0   7.92        S

**2.2** How many rows and columns does `df` have?

In [189]:
# TODO 2.2
df.shape

(12, 6)

**2.3** Select just the `Sex` and `Fare` columns together (as a DataFrame).

In [190]:
s1=df['Sex']
s2=df['Fare']
df3=pd.concat([s1,s2],axis=1)
type(df3)

pandas.DataFrame

In [191]:
ser1=pd.Series(df["Sex"])
customdf=ser1.to_frame()
customdf['Fare']=ser1
customdf

       Sex    Fare
0     male    male
1   female  female
2   female  female
3   female  female
4     male    male
5     male    male
6     male    male
7   female  female
8   female  female
9   female  female
10    male    male
11  female  female

In [192]:
ser1=pd.Series(df["Sex"])
ser2=pd.Series(df['Fare'])
customdf=ser1.to_frame()
customdf['Fare']=ser2
customdf

       Sex   Fare
0     male   7.25
1   female  71.28
2   female   7.92
3   female  53.10
4     male   8.05
5     male   8.46
6     male  51.86
7   female  11.13
8   female  30.07
9   female  16.70
10    male   7.85
11  female  26.55

In [193]:
customdf

       Sex   Fare
0     male   7.25
1   female  71.28
2   female   7.92
3   female  53.10
4     male   8.05
5     male   8.46
6     male  51.86
7   female  11.13
8   female  30.07
9   female  16.70
10    male   7.85
11  female  26.55

In [194]:
customdf1=df[['Sex','Fare']]
customdf1

       Sex   Fare
0     male   7.25
1   female  71.28
2   female   7.92
3   female  53.10
4     male   8.05
5     male   8.46
6     male  51.86
7   female  11.13
8   female  30.07
9   female  16.70
10    male   7.85
11  female  26.55

In [195]:
# TODO 2.3  (hint: pass a list of column names)
pd.concat((df["Sex"],df["Fare"]),axis=1)

       Sex   Fare
0     male   7.25
1   female  71.28
2   female   7.92
3   female  53.10
4     male   8.05
5     male   8.46
6     male  51.86
7   female  11.13
8   female  30.07
9   female  16.70
10    male   7.85
11  female  26.55

In [196]:
df4=df[['Sex','Fare']]
df4

       Sex   Fare
0     male   7.25
1   female  71.28
2   female   7.92
3   female  53.10
4     male   8.05
5     male   8.46
6     male  51.86
7   female  11.13
8   female  30.07
9   female  16.70
10    male   7.85
11  female  26.55

**2.4** Use `.info()` to find out which column has missing values, and how many non-null entries it has.

In [197]:
# TODO 2.4
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  12 non-null     int64
 1   Pclass    12 non-null     int64
 2   Sex       12 non-null     str
 3   Age       10 non-null     float64
 4   Fare      12 non-null     float64
 5   Embarked  12 non-null     str
dtypes: float64(2), int64(2), str(2)
memory usage: 708.0 bytes

In [198]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Age']

0     22.0
1     38.0
2     26.0
3     35.0
4     29.8
5     29.8
6     54.0
7     27.0
8     14.0
9      4.0
10    20.0
11    58.0
Name: Age, dtype: float64

In [199]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  12 non-null     int64
 1   Pclass    12 non-null     int64
 2   Sex       12 non-null     str
 3   Age       12 non-null     float64
 4   Fare      12 non-null     float64
 5   Embarked  12 non-null     str
dtypes: float64(2), int64(2), str(2)
memory usage: 708.0 bytes

In [200]:
df.describe()

        Survived     Pclass        Age       Fare
count  12.000000  12.000000  12.000000  12.000000
mean    0.500000   2.250000  29.800000  25.018333
std     0.522233   0.965307  15.283979  22.164804
min     0.000000   1.000000   4.000000   7.250000
25%     0.000000   1.000000  21.500000   8.017500
50%     0.500000   3.000000  28.400000  13.915000
75%     1.000000   3.000000  35.750000  35.517500
max     1.000000   3.000000  58.000000  71.280000

In [201]:
df['Age'].unique()

array([22. , 38. , 26. , 35. , 29.8, 54. , 27. , 14. ,  4. , 20. , 58. ])

---
## Part 3 — Selecting rows and columns

**3.1** Use `iloc` to get the row in position 4 (the 5th row).

In [202]:
# TODO 3.1
df.iloc[4]

Survived       0
Pclass         3
Sex         male
Age         29.8
Fare        8.05
Embarked       S
Name: 4, dtype: object

**3.2** Use `loc` to get the `Age` and `Fare` of the rows labelled 0 through 3.

In [203]:
df.loc[0:3:,['Age','Fare']]

    Age   Fare
0  22.0   7.25
1  38.0  71.28
2  26.0   7.92
3  35.0  53.10

In [204]:
df.loc[:3:]

   Survived  Pclass     Sex   Age   Fare Embarked
0         0       3    male  22.0   7.25        S
1         1       1  female  38.0  71.28        C
2         1       3  female  26.0   7.92        S
3         1       1  female  35.0  53.10        S

In [205]:
# TODO 3.2
df.iloc[:3:]

   Survived  Pclass     Sex   Age   Fare Embarked
0         0       3    male  22.0   7.25        S
1         1       1  female  38.0  71.28        C
2         1       3  female  26.0   7.92        S

**3.3** Select all passengers whose `Age` is greater than 30.

In [206]:
# TODO 3.3
aggr30=df.Age>30
df[aggr30]

    Survived  Pclass     Sex   Age   Fare Embarked
1          1       1  female  38.0  71.28        C
3          1       1  female  35.0  53.10        S
6          0       1    male  54.0  51.86        S
11         1       1  female  58.0  26.55        C

**3.4** Select all passengers who are in first class (`Pclass == 1`) **and** female.
*(Remember: wrap each condition in parentheses.)*

In [207]:
# TODO 3.4
df[(df['Pclass']==1) &(df['Sex']=='female')]

    Survived  Pclass     Sex   Age   Fare Embarked
1          1       1  female  38.0  71.28        C
3          1       1  female  35.0  53.10        S
11         1       1  female  58.0  26.55        C

**3.5** Show the `Sex`, `Pclass`, and `Fare` of everyone who paid **more than the average fare**.

In [208]:
# TODO 3.5  (the mask can contain a statistic)
avg_fare=df['Fare'].mean()
df[df['Fare']>avg_fare][['Sex','Pclass','Fare']]

       Sex  Pclass   Fare
1   female       1  71.28
3   female       1  53.10
6     male       1  51.86
8   female       3  30.07
11  female       1  26.55

---
## Part 4 — `describe()` and statistics

**4.1** Print the summary statistics for all numeric columns.

In [209]:
# TODO 4.1
df.describe()

        Survived     Pclass        Age       Fare
count  12.000000  12.000000  12.000000  12.000000
mean    0.500000   2.250000  29.800000  25.018333
std     0.522233   0.965307  15.283979  22.164804
min     0.000000   1.000000   4.000000   7.250000
25%     0.000000   1.000000  21.500000   8.017500
50%     0.500000   3.000000  28.400000  13.915000
75%     1.000000   3.000000  35.750000  35.517500
max     1.000000   3.000000  58.000000  71.280000

**4.2** From `describe()` (or directly), what is the **median** `Fare`? Compute it two ways — with `.median()` and by reading the 50% row of `describe()` — and confirm they match.

In [210]:
# TODO 4.2
print("median() :", np.median(df['Fare']))
print("describe :", df["Fare"].describe()["50%"])   # hint: df["Fare"].describe()["50%"]

median() : 13.915
describe : 13.915

**4.3** What is the standard deviation of `Age`? (Missing values are ignored automatically.)

In [211]:
# TODO 4.3
df['Age'].std()

np.float64(15.28397853963424)

In [212]:
np.std(df['Age'])

np.float64(14.63329536821195)

In [213]:
df['Age'].describe()['std']

np.float64(15.28397853963424)

In [214]:
df

    Survived  Pclass     Sex   Age   Fare Embarked
0          0       3    male  22.0   7.25        S
1          1       1  female  38.0  71.28        C
2          1       3  female  26.0   7.92        S
3          1       1  female  35.0  53.10        S
4          0       3    male  29.8   8.05        S
5          0       3    male  29.8   8.46        Q
6          0       1    male  54.0  51.86        S
7          0       3  female  27.0  11.13        S
8          1       3  female  14.0  30.07        S
9          1       2  female   4.0  16.70        S
10         0       3    male  20.0   7.85        S
11         1       1  female  58.0  26.55        C

---
## Part 5 — Classifying data types

**5.1** In the markdown cell below, classify each column as *quantitative (continuous/discrete)* or *qualitative (nominal/ordinal/binary)*. Fill in the blanks.

*(edit this cell — replace each ??? )*

| Column | Your classification |
|---|---|
| Survived | ??? |discrete
| Pclass | ??? |discrete
| Sex | ??? |nominal
| Age | ??? |continuos
| Fare | ??? |continous
| Embarked | ?? |nominal

**5.2** Use `value_counts()` on `Embarked`. Which port is the **mode** (most common)?

In [215]:
# TODO 5.2
df['Embarked'].value_counts()

Embarked
S    9
C    2
Q    1
Name: count, dtype: int64

In [216]:
import scipy as stats

In [217]:
df['Embarked'].value_counts().mode()

0    1
1    2
2    9
Name: count, dtype: int64

---
## Part 6 — Everyday operations

**6.1** How many *distinct* passenger classes are there? (Use `nunique()`.)

In [218]:
# TODO 6.1
df.nunique()

Survived     2
Pclass       3
Sex          2
Age         11
Fare        12
Embarked     3
dtype: int64

**6.2** Create a new column `age_group` that is `"adult"` if `Age >= 18` and `"child"` otherwise. Use `apply()` with a lambda.
*(Note: missing ages will need handling — for now, a passenger with a missing age will produce `"child"` because `np.nan >= 18` is False. That's fine for this exercise; we fix missing data next session.)*

In [219]:
# TODO 6.2
df["age_group"] = df["Age"].apply(lambda x:'adult'  if   x>=18  else  'child')
df[["Age", "age_group"]]

     Age age_group
0   22.0     adult
1   38.0     adult
2   26.0     adult
3   35.0     adult
4   29.8     adult
5   29.8     adult
6   54.0     adult
7   27.0     adult
8   14.0     child
9    4.0     child
10  20.0     adult
11  58.0     adult

In [220]:
df

    Survived  Pclass     Sex   Age   Fare Embarked age_group
0          0       3    male  22.0   7.25        S     adult
1          1       1  female  38.0  71.28        C     adult
2          1       3  female  26.0   7.92        S     adult
3          1       1  female  35.0  53.10        S     adult
4          0       3    male  29.8   8.05        S     adult
5          0       3    male  29.8   8.46        Q     adult
6          0       1    male  54.0  51.86        S     adult
7          0       3  female  27.0  11.13        S     adult
8          1       3  female  14.0  30.07        S     child
9          1       2  female   4.0  16.70        S     child
10         0       3    male  20.0   7.85        S     adult
11         1       1  female  58.0  26.55        C     adult

**6.3** Sort the whole DataFrame by `Fare`, highest first, and show the top 3 rows.

In [221]:
# TODO 6.3
a=sorted(df['Fare'])
a[-1::-1]

[71.28, 53.1, 51.86, 30.07, 26.55, 16.7, 11.13, 8.46, 8.05, 7.92, 7.85, 7.25]

In [222]:
d=sorted(df['Fare'])[-1::-1]

In [246]:
def rev(l):
    sl=sorted(l)
    c=reversed(sl)
    return c

In [255]:
check=[ 7.25, 71.28,  7.92, 53.1 ,  8.05,  8.46, 51.86, 11.13, 30.07,
       16.7 ,  7.85, 26.55]

In [256]:
print(reversed(check))

<list_reverseiterator object at 0x00000234E811E3E0>

In [ ]:
print(reversed(check))

In [248]:
rev(check)

In [257]:
np.array(df['Fare'])

array([ 7.25, 71.28,  7.92, 53.1 ,  8.05,  8.46, 51.86, 11.13, 30.07,
       16.7 ,  7.85, 26.55])

In [225]:
df['Fare']=df['Fare'].apply(lambda list: sorted(list)[::-1])

TypeError: 'float' object is not iterable

In [ ]:
df['Fare']

0     71.28
1     71.28
2     71.28
3     71.28
4     71.28
5     71.28
6     71.28
7     71.28
8     71.28
9     71.28
10    71.28
11    71.28
Name: Fare, dtype: float64

In [259]:
df['Fare']=df['Fare'].sort_values(ascending=False).values
df['Fare']

0     71.28
1     53.10
2     51.86
3     30.07
4     26.55
5     16.70
6     11.13
7      8.46
8      8.05
9      7.92
10     7.85
11     7.25
Name: Fare, dtype: float64

In [ ]:
df.head(3)

   Survived  Pclass     Sex   Age   Fare Embarked age_group
0         0       3    male  22.0  71.28        S     adult
1         1       1  female  38.0  53.10        C     adult
2         1       3  female  26.0  51.86        S     adult

**6.4** Count the missing values in every column.

In [262]:
# TODO 6.4
df.value_counts()

Survived  Pclass  Sex     Age   Fare   Embarked  age_group
0         3       male    22.0  71.28  S         adult        1
1         1       female  38.0  53.10  C         adult        1
          3       female  26.0  51.86  S         adult        1
          1       female  35.0  30.07  S         adult        1
0         3       male    29.8  26.55  S         adult        1
                                16.70  Q         adult        1
          1       male    54.0  11.13  S         adult        1
          3       female  27.0  8.46   S         adult        1
1         3       female  14.0  8.05   S         child        1
          2       female  4.0   7.92   S         child        1
0         3       male    20.0  7.85   S         adult        1
1         1       female  58.0  7.25   C         adult        1
Name: count, dtype: int64

In [263]:
df

    Survived  Pclass     Sex   Age   Fare Embarked age_group
0          0       3    male  22.0  71.28        S     adult
1          1       1  female  38.0  53.10        C     adult
2          1       3  female  26.0  51.86        S     adult
3          1       1  female  35.0  30.07        S     adult
4          0       3    male  29.8  26.55        S     adult
5          0       3    male  29.8  16.70        Q     adult
6          0       1    male  54.0  11.13        S     adult
7          0       3  female  27.0   8.46        S     adult
8          1       3  female  14.0   8.05        S     child
9          1       2  female   4.0   7.92        S     child
10         0       3    male  20.0   7.85        S     adult
11         1       1  female  58.0   7.25        C     adult

---
## Challenge (optional)

**C.1** Using a single line, find the **survival rate of female passengers** — the fraction of females who survived. 
*(Hint: filter to females, then take the mean of their `Survived` column. Because Survived is 0/1, its mean IS the survival rate.)*

In [277]:
# TODO
fsurv=df['Sex'].apply(lambda s:'1' if s=='female' else pass)

SyntaxError: invalid syntax (1016507403.py, line 2)

In [286]:
f=df['Sex']=='female'

In [295]:
f.mean()

np.float64(0.5833333333333334)

In [293]:
f.mean()

np.float64(0.5833333333333334)

In [300]:
df[f]['Survived'].value_counts(0)

Survived
1    6
0    1
Name: count, dtype: int64

In [301]:
df[f]['Survived'].value_counts(1)

Survived
1    0.857143
0    0.142857
Name: proportion, dtype: float64

In [302]:
(6/7)*100

85.71428571428571

**C.2** Which passenger class paid the highest *average* fare? Compute the mean `Fare` for each `Pclass`.
*(Hint: you can filter each class and take the mean, or peek ahead to `groupby` — either is fine.)*

In [314]:
df['Fare'].mean()

np.float64(25.018333333333334)

In [304]:
# TODO C.2
df[['Fare','Pclass']]

     Fare  Pclass
0   71.28       3
1   53.10       1
2   51.86       3
3   30.07       1
4   26.55       3
5   16.70       3
6   11.13       1
7    8.46       3
8    8.05       3
9    7.92       2
10   7.85       3
11   7.25       1

In [318]:
c=df.groupby('Pclass')['Fare'].mean()
c

Pclass
1    25.3875
2     7.9200
3    27.2500
Name: Fare, dtype: float64

In [317]:
c.idxmax()

np.int64(3)

---