# Week 4 · Day 4 — Exercises: Missing Data, GroupBy, Merging & Correlation

Practice for cleaning, grouping, binning, joining and correlating.

**How to work:**
- Fill in each cell where you see `...` or a `# TODO`.
- Run your cell and check the output makes sense before moving on.
- When finished: `Kernel → Restart & Run All`,

Setup — run this first. It loads the same dataset used in the practical lab.

In [313]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"C:\artificial_intelligence_coarse\sir_git_ai\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\students.csv")
city_info = pd.read_csv(r"C:\artificial_intelligence_coarse\sir_git_ai\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\city_info.csv")
print("students :", df.shape)
print("city_info:", city_info.shape)
df.head()

students : (184, 10)
city_info: (6, 3)

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

---
## Part 1 — Missing data

**1.1** Count the missing values in each column of `df`.

In [283]:
# TODO 1.1
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   184 non-null    str
 1   gender       184 non-null    str
 2   city         184 non-null    str
 3   program      184 non-null    str
 4   semester     184 non-null    int64
 5   study_hours  179 non-null    float64
 6   attendance   168 non-null    float64
 7   prev_gpa     174 non-null    float64
 8   final_marks  184 non-null    float64
 9   scholarship  184 non-null    int64
dtypes: float64(4), int64(2), str(4)
memory usage: 14.5 KB

In [284]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [285]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

**1.2** Express those missing values as a **percentage** of the total number of rows, rounded to 1 decimal place.

In [286]:
# TODO 1.2  (hint: divide by len(df), multiply by 100
(((df.isnull().sum())/len(df))*100).round(2)

student_id     0.00
gender         0.00
city           0.00
program        0.00
semester       0.00
study_hours    2.72
attendance     8.70
prev_gpa       5.43
final_marks    0.00
scholarship    0.00
dtype: float64

**1.3** How many rows would survive if you dropped every row containing any missing value? Compare that to the original row count.
*(Use `dropna()` — but do not overwrite `df`.)*

In [287]:
# TODO 1.3
print("original:", df.shape[0])
print("after dropna:", df.dropna().shape[0])

original: 184
after dropna: 154

In [288]:
df.gender.unique()

<StringArray>
['Female', 'Male', 'male', 'female']
Length: 4, dtype: str

**1.4** For `study_hours`, print the **mean**, the **median**, and the **skew**. Based on the skew, which is the safer value to fill missing entries with?

In [289]:
# TODO 1.4
print("mean  :", df['study_hours'].mean())
print("median:", df['study_hours'].median())
print("skew  :", df['study_hours'].skew())
# ANSWER: ...

mean  : 7.256983240223463
median: 6.4
skew  : 1.4934311595344316

**1.5** Fill the missing values in `study_hours`, `attendance` and `prev_gpa` with each column's **median**. Then confirm no missing values remain.

In [290]:
# TODO 1.5
for col in ["study_hours", "attendance", "prev_gpa"]:
    df[col] = df[col].fillna(df[col].median())

print("remaining missing:", df.isnull().sum())

remaining missing: student_id     0
gender         0
city           0
program        0
semester       0
study_hours    0
attendance     0
prev_gpa       0
final_marks    0
scholarship    0
dtype: int64

**1.6** Before grouping, the text columns need cleaning. Print the unique values of `gender` and `city` — what problem do you see? Fix both columns using `.str.strip().str.title()`, then print the unique values again.

In [291]:
df['gender']

0      Female
1      Female
2      Female
3      Female
4        Male
        ...
179    Female
180    Female
181      Male
182      Male
183      Male
Name: gender, Length: 184, dtype: str

In [292]:
print("BEFORE ",df['gender'].unique(),df['gender'].unique())

BEFORE  <StringArray>
['Female', 'Male', 'male', 'female']
Length: 4, dtype: str <StringArray>
['Female', 'Male', 'male', 'female']
Length: 4, dtype: str

In [293]:
df['city']=df['city'].str.strip().str.title()

In [294]:
df['city'].unique()

<StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str

In [295]:
df['gender']=df['gender'].str.strip().str.title()
df['gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [296]:
print("BEFORE ",df['gender'].unique())
print(df['city'].unique())
df['gender']=df['gender'].apply(lambda s: s.title())

BEFORE  <StringArray>
['Female', 'Male']
Length: 2, dtype: str
<StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str

In [297]:
df['gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [298]:
# TODO 1.6
print(f"BEFORE: {df["gender"].unique()}  {df["city"].unique()}")

df["gender"] = df["gender"].apply(lambda s: s.title())
df["city"] = df['city'].apply(lambda s: s.title())

print("AFTER :", df["gender"].unique(), df["city"].unique())
# PROBLEM: ...

BEFORE: <StringArray>
['Female', 'Male']
Length: 2, dtype: str  <StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str
AFTER : <StringArray>
['Female', 'Male']
Length: 2, dtype: str <StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str

**1.7** Remove any duplicate rows. How many were there?

In [314]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [315]:
# TODO 1.7
print("duplicates:",df.duplicated().sum())
df =df.drop_duplicates(subset=['student_id'])
print("rows now:", len(df))

duplicates: 4
rows now: 180

---
## Part 2 — GroupBy

**2.1** What is the average `final_marks` for each `program`?

In [300]:
# TODO 2.1
...

Ellipsis

**2.2** Same question, but sorted from highest to lowest average.

In [301]:
# TODO 2.2
...

Ellipsis

**2.3** For each `program`, show the **count**, **mean** and **standard deviation** of `final_marks` in one table.
*(Why does the count matter when reading a group average?)*

In [302]:
# TODO 2.3  (hint: .agg([...]))
...
# WHY COUNT MATTERS: ...

Ellipsis

**2.4** What is the average `attendance` for each `city`?

In [303]:
# TODO 2.4
...

Ellipsis

**2.5** Group by **two** columns: the average `final_marks` for each combination of `program` and `gender`.

In [304]:
# TODO 2.5
...

Ellipsis

**2.6** The `scholarship` column holds 0 or 1. Compute the **scholarship rate as a percentage** for each `program`.
*(Hint: the mean of a 0/1 column is the proportion of 1s.)*

In [305]:
# TODO 2.6
...

Ellipsis

**2.7** Use a dictionary inside `.agg()` to produce, for each `program`: the mean `final_marks`, the median `prev_gpa`, and the count of `student_id`.

In [306]:
# TODO 2.7
...

Ellipsis

---
## Part 3 — Discretization (binning)

**3.1** Create a new column `grade` from `final_marks` using these bands:
`0–50 → F`, `50–60 → D`, `60–70 → C`, `70–80 → B`, `80–100 → A`.
Then show the count of students in each grade.

In [307]:
# TODO 3.1  (hint: pd.cut with bins=[...] and labels=[...])
df["grade"] = ...
...

Ellipsis

**3.2** Create a column `attendance_band` splitting `attendance` into `low` (0–70), `medium` (70–85), `high` (85–100). Then find the average `final_marks` for each band.
*(What does the result suggest?)*

In [308]:
# TODO 3.2
df["attendance_band"] = ...
...
# OBSERVATION: ...

Ellipsis

**3.3** Use `apply()` with a lambda to create `study_level`: `"high"` if `study_hours >= 10`, `"medium"` if `>= 5`, otherwise `"low"`. Then show how many students fall in each level.

In [309]:
# TODO 3.3
df["study_level"] = df["study_hours"].apply(lambda h: ...)
...

Ellipsis

---
## Part 4 — Merging

**4.1** Display the `city_info` lookup table. Which column is shared with `df`?

In [310]:
# TODO 4.1
...
# SHARED COLUMN: ...

Ellipsis

**4.2** Merge `city_info` into `df` with a **left** join on `city`. Then verify the merge: the row count should be unchanged, and there should be no missing `province` values.

In [311]:
# TODO 4.2
rows_before = len(df)
df = ...

print("rows before:", rows_before, "| rows after:", len(df))
print("unmatched cities:", ...)

TypeError: object of type 'ellipsis' has no len()

**4.3** Why is `how="left"` the right choice here rather than `how="inner"`?

*(Answer in this markdown cell.)*

**ANSWER:** ...

**4.4** Now that provinces are attached, find the average `final_marks` and the student count for each `province`.

In [ ]:
# TODO 4.4
...

**4.5** Compare the average `final_marks` between `Main` and `Satellite` campuses.

In [ ]:
# TODO 4.5
...

**4.6** Practise the join types on small tables. Given the two tables below, produce an **inner** join and a **left** join, and note which rows disappear in each.

In [ ]:
students_small = pd.DataFrame({
    "roll": [1, 2, 3, 4],
    "name": ["Ali", "Sara", "Bilal", "Ayesha"],
    "course_id": [101, 102, 101, 999],
})
courses = pd.DataFrame({
    "course_id": [101, 102, 103],
    "course_name": ["Python", "Statistics", "Databases"],
})
print(students_small, "\n")
print(courses)

In [ ]:
# TODO 4.6a: inner join
...

# TODO 4.6b: left join
...

# WHAT DISAPPEARS: ...

---
## Part 5 — Correlation

**5.1** Build a correlation matrix for `study_hours`, `attendance`, `prev_gpa` and `final_marks`, rounded to 3 decimals.

In [ ]:
# TODO 5.1
numeric = ["study_hours", "attendance", "prev_gpa", "final_marks"]
...

**5.2** Extract just the correlations **with `final_marks`**, drop the self-correlation, and sort them from strongest to weakest. Which factor tracks final marks most closely?

In [ ]:
# TODO 5.2
...
# STRONGEST: ...

**5.3** Compute the correlation between just `attendance` and `final_marks` as a single number. Using the guide (below 0.3 weak, 0.3–0.6 moderate, above 0.6 strong), how would you describe it?

In [ ]:
# TODO 5.3
...
# DESCRIPTION: ...

**5.4** Why can we **not** conclude from 5.2 that studying more *causes* higher marks? Give one plausible alternative explanation.

*(Answer in this markdown cell.)*

**ANSWER:** ...

---
## Challenge (optional)

**C.1** Among students who received a scholarship, what is the average `final_marks`? Compare it with those who did not.
*(One line, using groupby.)*

In [ ]:
# TODO C.1
...

**C.2** Build a table showing the average `final_marks` for every combination of `study_level` and `attendance_band`.
*(Which combination performs best? Check the group sizes before trusting the result.)*

In [ ]:
# TODO C.2
...

**C.3** Write a short summary of what you found in this dataset — 3 bullet points, plain English, each backed by a number you computed above.

*(Write your answer here.)*

1. 
2. 
3.

---