# Week 4 · Day 4 — Exercises: Missing Data, GroupBy, Merging & Correlation

Practice for cleaning, grouping, binning, joining and correlating.

**How to work:**
- Fill in each cell where you see `...` or a `# TODO`.
- Run your cell and check the output makes sense before moving on.
- When finished: `Kernel → Restart & Run All`,

Setup — run this first. It loads the same dataset used in the practical lab.

In [3190]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"C:\artificial_intelligence_coarse\sir_git_ai\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\students.csv")
city_info = pd.read_csv(r"C:\artificial_intelligence_coarse\sir_git_ai\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-04-libraries-descriptive-statistics\datasets\city_info.csv")
print("students :", df.shape)
print("city_info:", city_info.shape)
df.head()

students : (184, 10)
city_info: (6, 3)

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

---
## Part 1 — Missing data

**1.1** Count the missing values in each column of `df`.

In [3191]:
# TODO 1.1
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   184 non-null    str
 1   gender       184 non-null    str
 2   city         184 non-null    str
 3   program      184 non-null    str
 4   semester     184 non-null    int64
 5   study_hours  179 non-null    float64
 6   attendance   168 non-null    float64
 7   prev_gpa     174 non-null    float64
 8   final_marks  184 non-null    float64
 9   scholarship  184 non-null    int64
dtypes: float64(4), int64(2), str(4)
memory usage: 14.5 KB

In [3192]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

In [3193]:
df.isnull().sum()

student_id      0
gender          0
city            0
program         0
semester        0
study_hours     5
attendance     16
prev_gpa       10
final_marks     0
scholarship     0
dtype: int64

**1.2** Express those missing values as a **percentage** of the total number of rows, rounded to 1 decimal place.

In [3194]:
# TODO 1.2  (hint: divide by len(df), multiply by 100
(((df.isnull().sum())/len(df))*100).round(2)

student_id     0.00
gender         0.00
city           0.00
program        0.00
semester       0.00
study_hours    2.72
attendance     8.70
prev_gpa       5.43
final_marks    0.00
scholarship    0.00
dtype: float64

**1.3** How many rows would survive if you dropped every row containing any missing value? Compare that to the original row count.
*(Use `dropna()` — but do not overwrite `df`.)*

In [3195]:
# TODO 1.3
print("original:", df.shape[0])
print("after dropna:", df.dropna().shape[0])

original: 184
after dropna: 154

In [3196]:
df.gender.unique()

<StringArray>
['Female', 'Male', 'male', 'female']
Length: 4, dtype: str

**1.4** For `study_hours`, print the **mean**, the **median**, and the **skew**. Based on the skew, which is the safer value to fill missing entries with?

In [3197]:
# TODO 1.4
print("mean  :", df['study_hours'].mean())
print("median:", df['study_hours'].median())
print("skew  :", df['study_hours'].skew())
# ANSWER: ...

mean  : 7.256983240223463
median: 6.4
skew  : 1.4934311595344316

**1.5** Fill the missing values in `study_hours`, `attendance` and `prev_gpa` with each column's **median**. Then confirm no missing values remain.

In [3198]:
# TODO 1.5
for col in ["study_hours", "attendance", "prev_gpa"]:
    df[col] = df[col].fillna(df[col].median())

print("remaining missing:", df.isnull().sum())

remaining missing: student_id     0
gender         0
city           0
program        0
semester       0
study_hours    0
attendance     0
prev_gpa       0
final_marks    0
scholarship    0
dtype: int64

**1.6** Before grouping, the text columns need cleaning. Print the unique values of `gender` and `city` — what problem do you see? Fix both columns using `.str.strip().str.title()`, then print the unique values again.

In [3199]:
df['gender']

0      Female
1      Female
2      Female
3      Female
4        Male
        ...
179    Female
180    Female
181      Male
182      Male
183      Male
Name: gender, Length: 184, dtype: str

In [3200]:
print("BEFORE ",df['gender'].unique(),df['gender'].unique())

BEFORE  <StringArray>
['Female', 'Male', 'male', 'female']
Length: 4, dtype: str <StringArray>
['Female', 'Male', 'male', 'female']
Length: 4, dtype: str

In [3201]:
df['city']=df['city'].str.strip().str.title()

In [3202]:
df['city'].unique()

<StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str

In [3203]:
df['gender']=df['gender'].str.strip().str.title()
df['gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [3204]:
print("BEFORE ",df['gender'].unique())
print(df['city'].unique())
df['gender']=df['gender'].apply(lambda s: s.title())

BEFORE  <StringArray>
['Female', 'Male']
Length: 2, dtype: str
<StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str

In [3205]:
df['gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [3206]:
# TODO 1.6
print(f"BEFORE: {df["gender"].unique()}  {df["city"].unique()}")

df["gender"] = df["gender"].apply(lambda s: s.title())
df["city"] = df['city'].apply(lambda s: s.title())

print("AFTER :", df["gender"].unique(), df["city"].unique())
# PROBLEM: ...

BEFORE: <StringArray>
['Female', 'Male']
Length: 2, dtype: str  <StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str
AFTER : <StringArray>
['Female', 'Male']
Length: 2, dtype: str <StringArray>
['Quetta', 'Karachi', 'Lahore', 'Peshawar', 'Multan', 'Islamabad']
Length: 6, dtype: str

**1.7** Remove any duplicate rows. How many were there?

In [3207]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.910,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,2.875,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,2.875,68.7,0
3,S1024,Female,Peshawar,BSCS,3,2.5,100.0,2.840,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,2.875,68.8,0

In [3208]:
# TODO 1.7
print("duplicates:",df.duplicated().sum())
df =df.drop_duplicates(subset=['student_id'])
print("rows now:", len(df))

duplicates: 4
rows now: 180

---
## Part 2 — GroupBy

**2.1** What is the average `final_marks` for each `program`?

In [3209]:
# TODO 2.1
df.groupby('program')['final_marks'].mean()

program
BBA     67.744186
BSCS    64.930556
BSEE    62.216000
BSSE    64.535000
Name: final_marks, dtype: float64

**2.2** Same question, but sorted from highest to lowest average.

In [3210]:
# TODO 2.2
df.groupby('program')['final_marks'].mean().sort_values(ascending=False)

program
BBA     67.744186
BSCS    64.930556
BSSE    64.535000
BSEE    62.216000
Name: final_marks, dtype: float64

**2.3** For each `program`, show the **count**, **mean** and **standard deviation** of `final_marks` in one table.
*(Why does the count matter when reading a group average?)*

In [3211]:
# TODO 2.3  (hint: .agg([...]))
df.groupby("program")['final_marks'].agg(["count","mean","std"]).round(2)
# WHY COUNT MATTERS: ...

         count   mean    std
program
BBA         43  67.74  12.24
BSCS        72  64.93  11.62
BSEE        25  62.22  10.22
BSSE        40  64.54  11.43

**2.4** What is the average `attendance` for each `city`?

In [3212]:
# TODO 2.4
df.groupby("city")['attendance'].mean().sort_values(ascending=False)

city
Islamabad    83.835000
Peshawar     83.391379
Karachi      81.913889
Lahore       81.168966
Quetta       81.114286
Multan       80.825000
Name: attendance, dtype: float64

**2.5** Group by **two** columns: the average `final_marks` for each combination of `program` and `gender`.

In [3213]:
# TODO 2.5
df.groupby(["program",'gender'])["final_marks"].mean()

program  gender
BBA      Female    66.785000
         Male      68.578261
BSCS     Female    65.211538
         Male      64.771739
BSEE     Female    64.550000
         Male      60.061538
BSSE     Female    60.293333
         Male      67.080000
Name: final_marks, dtype: float64

**2.6** The `scholarship` column holds 0 or 1. Compute the **scholarship rate as a percentage** for each `program`.
*(Hint: the mean of a 0/1 column is the proportion of 1s.)*

In [3214]:
# TODO 2.6
df.groupby("program")["scholarship"].count()/(len("scholarship")*100)

program
BBA     0.039091
BSCS    0.065455
BSEE    0.022727
BSSE    0.036364
Name: scholarship, dtype: float64

**2.7** Use a dictionary inside `.agg()` to produce, for each `program`: the mean `final_marks`, the median `prev_gpa`, and the count of `student_id`.

In [3215]:
# TODO 2.7
df.groupby("program").agg({"final_marks":"mean","prev_gpa":"median","student_id":"count"})

         final_marks  prev_gpa  student_id
program
BBA        67.744186     2.870          43
BSCS       64.930556     2.875          72
BSEE       62.216000     2.980          25
BSSE       64.535000     2.955          40

---
## Part 3 — Discretization (binning)

**3.1** Create a new column `grade` from `final_marks` using these bands:
`0–50 → F`, `50–60 → D`, `60–70 → C`, `70–80 → B`, `80–100 → A`.
Then show the count of students in each grade.

In [3216]:
# TODO 3.1  (hint: pd.cut with bins=[...] and labels=[...])
df["grade"] = pd.cut(df['final_marks'],
                     bins=[0,50,60,70,80,100],
                     labels=['F','D','C','B','A'])

In [3217]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,grade
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.910,68.5,0,C
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,2.875,54.4,0,D
2,S1131,Female,Lahore,BBA,7,4.0,96.9,2.875,68.7,0,C
3,S1024,Female,Peshawar,BSCS,3,2.5,100.0,2.840,56.8,0,D
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,2.875,68.8,0,C

**3.2** Create a column `attendance_band` splitting `attendance` into `low` (0–70), `medium` (70–85), `high` (85–100). Then find the average `final_marks` for each band.
*(What does the result suggest?)*

In [3218]:
# TODO 3.2
df["attendance_band"] = pd.cut(
    df["attendance"],
    bins=[0,70,85,100],
    labels=["low","medium","high"]
)
lowavg=df.groupby("attendance_band")['final_marks'].mean().sort_values(ascending=False)
lowavg
# OBSERVATION: what a fantastics coding of python pandas providing such a vast facility of grouping and making new column based on
#  existing one with multiple condition using bins and labels

attendance_band
high      68.278462
medium    64.146739
low       60.226087
Name: final_marks, dtype: float64

**3.3** Use `apply()` with a lambda to create `study_level`: `"high"` if `study_hours >= 10`, `"medium"` if `>= 5`, otherwise `"low"`. Then show how many students fall in each level.

In [3219]:
# TODO 3.3
df["study_level"] = df["study_hours"].apply(lambda h: "high" if h >=10 else ("medium" if h >=5 else 'low'))
df[["study_hours","final_marks","study_level"]].head(10)

   study_hours  final_marks study_level
0          8.1         68.5      medium
1          5.2         54.4      medium
2          4.0         68.7         low
3          2.5         56.8         low
4          7.7         68.8      medium
5          7.6         55.4      medium
6          0.5         48.3         low
7          2.7         62.5         low
8         30.0         92.4        high
9         15.0         79.3        high

---
## Part 4 — Merging

**4.1** Display the `city_info` lookup table. Which column is shared with `df`?

In [3220]:
city_info.head(0)

Empty DataFrame
Columns: [city, province, campus_type]
Index: []

In [3221]:
# TODO 4.1
df.head()
# SHARED COLUMN: ...

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,grade,attendance_band,study_level
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.910,68.5,0,C,high,medium
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,2.875,54.4,0,D,medium,medium
2,S1131,Female,Lahore,BBA,7,4.0,96.9,2.875,68.7,0,C,high,low
3,S1024,Female,Peshawar,BSCS,3,2.5,100.0,2.840,56.8,0,D,high,low
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,2.875,68.8,0,C,high,medium

**4.2** Merge `city_info` into `df` with a **left** join on `city`. Then verify the merge: the row count should be unchanged, and there should be no missing `province` values.

In [3222]:
# TODO 4.2
rows_before = len(df)
df = pd.merge(df,city_info,on='city',how='left')

print("rows before:", rows_before, "| rows after:", len(df))
print("unmatched cities:",df['province'].isnull().sum())

rows before: 180 | rows after: 180
unmatched cities: 0

In [3223]:
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,grade,attendance_band,study_level,province,campus_type
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.910,68.5,0,C,high,medium,Balochistan,Satellite
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,2.875,54.4,0,D,medium,medium,Sindh,Main
2,S1131,Female,Lahore,BBA,7,4.0,96.9,2.875,68.7,0,C,high,low,Punjab,Main
3,S1024,Female,Peshawar,BSCS,3,2.5,100.0,2.840,56.8,0,D,high,low,Khyber Pakhtunkhwa,Main
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,2.875,68.8,0,C,high,medium,Balochistan,Satellite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.730,56.0,1,D,low,medium,Khyber Pakhtunkhwa,Main
176,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.370,63.5,0,C,medium,low,Khyber Pakhtunkhwa,Main
177,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.140,65.3,0,C,medium,low,Punjab,Main
178,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.350,71.5,0,B,high,medium,Khyber Pakhtunkhwa,Main
179,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.040,57.8,0,D,medium,medium,Sindh,Main

**4.3** Why is `how="left"` the right choice here rather than `how="inner"`?

*(Answer in this markdown cell.)*

**ANSWER:** ...

**4.4** Now that provinces are attached, find the average `final_marks` and the student count for each `province`.

In [3224]:
# TODO 4.4
df.groupby('province')['final_marks'].mean()

province
Balochistan                    67.966667
Islamabad Capital Territory    67.185000
Khyber Pakhtunkhwa             66.681034
Punjab                         62.902222
Sindh                          62.658333
Name: final_marks, dtype: float64

In [3225]:
df.groupby('province')['final_marks'].max()

province
Balochistan                    85.8
Islamabad Capital Territory    88.4
Khyber Pakhtunkhwa             92.4
Punjab                         83.0
Sindh                          85.5
Name: final_marks, dtype: float64

In [3226]:
df.groupby('province')['final_marks'].min()

province
Balochistan                    48.2
Islamabad Capital Territory    40.9
Khyber Pakhtunkhwa             38.1
Punjab                         32.1
Sindh                          42.1
Name: final_marks, dtype: float64

In [3227]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       180 non-null    str
 1   gender           180 non-null    str
 2   city             180 non-null    str
 3   program          180 non-null    str
 4   semester         180 non-null    int64
 5   study_hours      180 non-null    float64
 6   attendance       180 non-null    float64
 7   prev_gpa         180 non-null    float64
 8   final_marks      180 non-null    float64
 9   scholarship      180 non-null    int64
 10  grade            180 non-null    category
 11  attendance_band  180 non-null    category
 12  study_level      180 non-null    str
 13  province         180 non-null    str
 14  campus_type      180 non-null    str
dtypes: category(2), float64(4), int64(2), str(7)
memory usage: 18.9 KB

**4.5** Compare the average `final_marks` between `Main` and `Satellite` campuses.

In [3228]:
# TODO 4.5
df.groupby('campus_type')['final_marks'].mean()

campus_type
Main         64.769106
Satellite    65.933333
Name: final_marks, dtype: float64

**4.6** Practise the join types on small tables. Given the two tables below, produce an **inner** join and a **left** join, and note which rows disappear in each.

In [3229]:
students_small = pd.DataFrame({
    "roll": [1, 2, 3, 4],
    "name": ["Ali", "Sara", "Bilal", "Ayesha"],
    "course_id": [101, 102, 101, 999],
})
courses = pd.DataFrame({
    "course_id": [101, 102, 103],
    "course_name": ["Python", "Statistics", "Databases"],
})
print(students_small, "\n")
print(courses)

   roll    name  course_id
0     1     Ali        101
1     2    Sara        102
2     3   Bilal        101
3     4  Ayesha        999

   course_id course_name
0        101      Python
1        102  Statistics
2        103   Databases

In [3230]:
#students_small=pd.merge(right=students_small,on='course_id',left=courses,how='inner')
students_small

   roll    name  course_id
0     1     Ali        101
1     2    Sara        102
2     3   Bilal        101
3     4  Ayesha        999

In [3231]:
# TODO 4.6a: inner join
students_small=pd.merge(left=students_small,on='course_id',right=courses,how='inner')
print(students_small)
# TODO 4.6b: left join
students_small=pd.merge(students_small,courses,on='course_id',how='left')
print(students_small)

# WHAT DISAPPEARS: ...
# the remaining line with no matching code for course disappear

   roll   name  course_id course_name
0     1    Ali        101      Python
1     2   Sara        102  Statistics
2     3  Bilal        101      Python
   roll   name  course_id course_name_x course_name_y
0     1    Ali        101        Python        Python
1     2   Sara        102    Statistics    Statistics
2     3  Bilal        101        Python        Python

---
## Part 5 — Correlation

**5.1** Build a correlation matrix for `study_hours`, `attendance`, `prev_gpa` and `final_marks`, rounded to 3 decimals.

In [3232]:
# TODO 5.1
numeric = ["study_hours", "attendance", "prev_gpa", "final_marks"]
finalmacorr=df[numeric].corr()
finalmacorr

             study_hours  attendance  prev_gpa  final_marks
study_hours     1.000000   -0.033066  0.056414     0.655171
attendance     -0.033066    1.000000  0.008452     0.300140
prev_gpa        0.056414    0.008452  1.000000     0.279630
final_marks     0.655171    0.300140  0.279630     1.000000

In [3233]:
type(finalmacorr)

pandas.DataFrame

**5.2** Extract just the correlations **with `final_marks`**, drop the self-correlation, and sort them from strongest to weakest. Which factor tracks final marks most closely?

In [3234]:
finalmacorr.iloc[::,-1].sort_values(ascending=False)

final_marks    1.000000
study_hours    0.655171
attendance     0.300140
prev_gpa       0.279630
Name: final_marks, dtype: float64

In [3235]:
# TODO 5.2
df[['study_hours','attendance','prev_gpa']].corr()
# STRONGEST: ...

             study_hours  attendance  prev_gpa
study_hours     1.000000   -0.033066  0.056414
attendance     -0.033066    1.000000  0.008452
prev_gpa        0.056414    0.008452  1.000000

**5.3** Compute the correlation between just `attendance` and `final_marks` as a single number. Using the guide (below 0.3 weak, 0.3–0.6 moderate, above 0.6 strong), how would you describe it?

In [3236]:
# TODO 5.3

df[['attendance','final_marks']].corr()
# DESCRIPTION: correlation is moderate positive because both have a 0.30014 relation

             attendance  final_marks
attendance      1.00000      0.30014
final_marks     0.30014      1.00000

**5.4** Why can we **not** conclude from 5.2 that studying more *causes* higher marks? Give one plausible alternative explanation.

*(Answer in this markdown cell.)*

**ANSWER:** ...

yes we can use that greater the number of study hour greatER will be the marks but in reality it is completely opposite to it because 
the greatest value in study hour is 30 while lowest is 0 so a huge difference there and the median value of studyhour is 6 while standard deviation mean the max value from median as well as minimum value from median is 4,while the greater study hours is only increasing the total average study hour as well as final marks

---
## Challenge (optional)

**C.1** Among students who received a scholarship, what is the average `final_marks`? Compare it with those who did not.
*(One line, using groupby.)*

In [3237]:
len(df[df['scholarship']==1])

76

In [3240]:
len(df[df['scholarship']==0])

104

In [ ]:
# TODO C.1
df.groupby('scholarship')["final_marks"].mean()

scholarship
0    64.221154
1    66.392105
Name: final_marks, dtype: float64

**C.2** Build a table showing the average `final_marks` for every combination of `study_level` and `attendance_band`.
*(Which combination performs best? Check the group sizes before trusting the result.)*

In [ ]:
# TODO C.2

Ellipsis

**C.3** Write a short summary of what you found in this dataset — 3 bullet points, plain English, each backed by a number you computed above.

*(Write your answer here.)*

1. 
2. 
3.

---